import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/Navbar.jsx';
import Footer from '@/app/components/Footer.jsx';

import Link from "next/link";
import StoreProvider from "./StoreProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Learning Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      > 
      <Navbar />
        <main className="flex-grow">
        <StoreProvider>
          {children}
        </StoreProvider>
          </main>
      <Footer />
      </body>
    </html>
  );
}
console.log('Hello Mostafa2');
